# Generated by Django 4.2.3 on 2023-08-07 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_cooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dish', to=settings.AUTH_USER_MODEL),
        ),
    ]
